Fixes #796 Adding provision to have a result enricher for workers
camunda-community-hub/spring-zeebe pull request #797
Opened 2024-05-23 15:39 UTC by hem-verma

We want to do additional processing on the incoming and outgoing variables of the worker before they can go into/come from SaaS. Adding the provision to have a custome result enricher.

2024-05-23 15:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda-community-hub/spring-zeebe?pullRequest=797) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda-community-hub/spring-zeebe?pullRequest=797) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda-community-hub/spring-zeebe?pullRequest=797) it.</sub>

2024-06-03 09:23 UTC, jonathanlukas requested changes
Thank you for your PR.

I really like the proposed change. However, I would like to reiterate on some details:

* `ResultEnricher` is a opinionated term, I would prefer `ResultProcessor`
* I would split up the `ResultProcessor` into 2 parts (this approach is equal to the `ParameterResolver`):
  * the actual `ResultProcessor` that is able to map the result
  * a `ResultProcessorStrategy` which allows for finding the right `ResultProcessor` for a `@JobWorker` function based on the available information 
* please add unit tests to verify the desired behaviour

2024-06-07 09:44 UTC, hem-verma commented
As seen in the screenshot, I have already agreed to the CLA but the same is not reflecting here. Not sure why. Any idea?

<img width="1246" alt="image" src="https://github.com/camunda-community-hub/spring-zeebe/assets/69243359/08cc692d-49da-41fa-81c4-145cd23bf764">

2024-06-07 09:51 UTC, jonathanlukas commented
I think @xomiamoore mentioned that the email address being used for the commit in the PR is different from the one being used to sign the CLA. Could you please verify this?

2024-06-07 11:10 UTC, hem-verma commented
That is weird. Seems like I have two accounts or maybe I had an account but later used google account to login again. But the account which created the PR should take the priority. Right? Any other account should be able to push changes as a contributor to the PR. Do you know how this can be fixed?

2024-06-07 11:12 UTC, jonathanlukas commented
@xomiamoore provided this guide: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

2024-06-07 11:18 UTC, hem-verma commented
Thanks I will check. I have the changes ready as suggested by you. But I have question about the Unit test. Could you please indicate/guide how to write that. I am confused because there is no unit test for JobHandlerInvokingSpringBeans. and there are not many tests available in the zeebe-client module.

2024-06-07 13:22 UTC, jonathanlukas commented
The unit test should be able to prove that your configuration is applied so that the beans that depend on the new feature are created correctly.

Also, customization options (like bean overriding) could be tested.

2024-06-07 14:14 UTC, hem-verma commented
May I ask if there are existing examples in the repo for testing the implementation for ParameterResolverStrategy? It will help me in understanding how much to test for ResultProcessor. I could not find anything in the folder src/test/java/io/camunda/zeebe/spring/client

2024-06-10 19:39 UTC, closed without merging

2024-06-10 19:59 UTC, hem-verma commented
Close this PR because of wrong account (mistakenly) being used for commit. Created a new PR with correct account. https://github.com/camunda-community-hub/spring-zeebe/pull/833

2024-06-11 04:55 UTC, jonathanlukas reviewed
lgtm